-- ============================================================================
-- 任务积分与收藏室（2026-08-17 迭代）
-- ----------------------------------------------------------------------------
-- 说明：
--   1. 与 wrong_questions 一致，这些表由前端使用 anon key 直接读写，
--      不启用 RLS；行归属通过 student_id（来自身份会话的 learnerId）约束。
--   2. 在 Supabase SQL Editor 中整体执行；可重复执行（全部使用 IF NOT EXISTS）。
--   3. 执行后可运行 `supabase db dump --linked -f database/baseline/schema.sql`
--      重新导出基线，使 schema.sql 与本文件保持一致。
-- ============================================================================

-- 账户积分：每个学习者一行，管理员点击「完成」后累加
CREATE TABLE IF NOT EXISTS public.user_points (
    student_id bigint PRIMARY KEY,
    points bigint NOT NULL DEFAULT 0 CHECK (points >= 0),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- 任务领取记录：同一任务只能领取一次积分
CREATE TABLE IF NOT EXISTS public.task_claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    task_id bigint NOT NULL,
    claimed_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT task_claims_student_task_unique UNIQUE (student_id, task_id)
);

CREATE INDEX IF NOT EXISTS task_claims_student_id_idx ON public.task_claims (student_id);

-- 卡片收藏：里程碑领取的卡片（一个里程碑只能领取一次）
CREATE TABLE IF NOT EXISTS public.card_collection (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    milestone_points bigint NOT NULL,
    card_key text NOT NULL,
    set_key text NOT NULL,
    rarity text NOT NULL CHECK (rarity IN ('common', 'rare')),
    claimed_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT card_collection_student_milestone_unique UNIQUE (student_id, milestone_points)
);

CREATE INDEX IF NOT EXISTS card_collection_student_id_idx ON public.card_collection (student_id);
