SET lock_timeout = '5s';
SET statement_timeout = '30s';

CREATE TABLE public.student (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL UNIQUE,
    permissions integer[] DEFAULT '{}'::integer[]
);

CREATE TABLE public.article_answer_keys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_id bigint NOT NULL,
    answer_text text DEFAULT ''::text NOT NULL,
    auto_grade boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    question_id text NOT NULL,
    CONSTRAINT article_answer_keys_blog_question_unique
        UNIQUE (blog_id, question_id)
);

CREATE INDEX idx_article_answer_keys_blog_id
    ON public.article_answer_keys (blog_id);

CREATE INDEX idx_article_answer_keys_question_id
    ON public.article_answer_keys (question_id);

CREATE TABLE public.article_question_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_id bigint NOT NULL,
    student_id bigint NOT NULL,
    answer_text text DEFAULT ''::text NOT NULL,
    review_status text DEFAULT 'pending'::text NOT NULL,
    review_result text,
    submitted_at timestamp with time zone DEFAULT now() NOT NULL,
    reviewed_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    question_id text NOT NULL,
    CONSTRAINT article_question_submissions_review_status_check
        CHECK (review_status = ANY (ARRAY['pending'::text, 'reviewed'::text])),
    CONSTRAINT article_question_submissions_review_result_check
        CHECK (review_result = ANY (ARRAY['correct'::text, 'partial'::text, 'wrong'::text])),
    CONSTRAINT article_question_submissions_blog_student_question_unique
        UNIQUE (blog_id, student_id, question_id),
    CONSTRAINT article_question_submissions_student_id_fkey
        FOREIGN KEY (student_id) REFERENCES public.student (id) ON DELETE CASCADE
);

CREATE INDEX idx_article_question_submissions_blog_student
    ON public.article_question_submissions (blog_id, student_id);

CREATE INDEX idx_article_question_submissions_question_id
    ON public.article_question_submissions (question_id);

CREATE INDEX idx_article_question_submissions_review_status
    ON public.article_question_submissions (review_status);

CREATE TABLE public.wrong_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    correct_answer text DEFAULT ''::text NOT NULL,
    my_answer text DEFAULT ''::text NOT NULL,
    wrong_reason text DEFAULT ''::text NOT NULL,
    tags text[] DEFAULT '{}'::text[] NOT NULL,
    note text DEFAULT ''::text NOT NULL,
    source_blog_id bigint,
    source_question_id text,
    is_manual boolean DEFAULT true NOT NULL,
    mastered boolean DEFAULT false NOT NULL,
    removed boolean DEFAULT false NOT NULL,
    wrong_count integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT wrong_questions_student_source_unique
        UNIQUE (student_id, source_blog_id, source_question_id)
);
