SET lock_timeout = '5s';
SET statement_timeout = '30s';

CREATE TABLE public.account (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    learner_id bigint UNIQUE REFERENCES public.student (id) ON DELETE RESTRICT,
    username text NOT NULL,
    username_normalized text NOT NULL,
    password_hash text,
    status text NOT NULL DEFAULT 'pending_activation',
    role text NOT NULL DEFAULT 'learner',
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    activated_at timestamp with time zone,
    CONSTRAINT account_username_trimmed_check CHECK (username = btrim(username)),
    CONSTRAINT account_username_normalized_check CHECK (username_normalized = lower(btrim(username))),
    CONSTRAINT account_status_check CHECK (status IN ('pending_activation', 'active', 'disabled')),
    CONSTRAINT account_role_check CHECK (role IN ('learner', 'administrator')),
    CONSTRAINT account_activation_state_check CHECK (
        (status = 'pending_activation' AND password_hash IS NULL AND activated_at IS NULL)
        OR (status = 'active' AND password_hash IS NOT NULL AND activated_at IS NOT NULL)
        OR status = 'disabled'
    )
);

CREATE UNIQUE INDEX account_username_normalized_unique ON public.account (username_normalized);

INSERT INTO public.account (id, learner_id, username, username_normalized, role)
SELECT id, id, btrim(username), lower(btrim(username)),
       CASE WHEN lower(btrim(username)) = 'young' THEN 'administrator' ELSE 'learner' END
FROM public.student;

SELECT setval(
    pg_get_serial_sequence('public.account', 'id'),
    COALESCE(MAX(id), 1),
    MAX(id) IS NOT NULL
)
FROM public.account;

CREATE TABLE public.account_activation (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL REFERENCES public.account (id) ON DELETE CASCADE,
    token_hash bytea NOT NULL UNIQUE,
    expires_at timestamp with time zone NOT NULL,
    consumed_at timestamp with time zone,
    revoked_at timestamp with time zone,
    created_by bigint REFERENCES public.account (id) ON DELETE SET NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT account_activation_expiry_check CHECK (expires_at > created_at),
    CONSTRAINT account_activation_terminal_state_check CHECK (
        consumed_at IS NULL OR revoked_at IS NULL
    )
);

CREATE INDEX account_activation_account_id_idx ON public.account_activation (account_id);
CREATE UNIQUE INDEX account_activation_one_live_per_account
    ON public.account_activation (account_id) WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE TABLE public.account_session (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash bytea NOT NULL UNIQUE,
    account_id bigint REFERENCES public.account (id) ON DELETE CASCADE,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    authenticated_at timestamp with time zone,
    revoked_at timestamp with time zone
);

CREATE INDEX account_session_account_id_idx ON public.account_session (account_id);
CREATE INDEX account_session_expires_at_idx ON public.account_session (expires_at);
