SET lock_timeout = '5s';
SET statement_timeout = '30s';

-- 每日签到记录：每个学习者每个自然日一行（服务端以 Asia/Shanghai 时区判定当日）
CREATE TABLE public.daily_check_in (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL REFERENCES public.student (id) ON DELETE CASCADE,
    check_in_date date NOT NULL,
    points_awarded bigint NOT NULL CHECK (points_awarded > 0),
    bonus_days smallint CHECK (bonus_days IN (7, 14)),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT daily_check_in_student_date_unique UNIQUE (student_id, check_in_date)
);

CREATE INDEX daily_check_in_student_date_desc_idx
    ON public.daily_check_in (student_id, check_in_date DESC);

-- 账户积分：生产库已通过 reconciliation SQL（2026-08-17_points_and_collection.sql）创建，
-- 这里以 IF NOT EXISTS 兜底，保证全新数据库迁移后该表也存在。
-- 后端（每日签到等）与前端（任务/里程碑）共用此表。
CREATE TABLE IF NOT EXISTS public.user_points (
    student_id bigint PRIMARY KEY,
    points bigint NOT NULL DEFAULT 0 CHECK (points >= 0),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);
