SET lock_timeout = '5s';
SET statement_timeout = '30s';

CREATE TABLE IF NOT EXISTS public.task_claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    task_id bigint NOT NULL,
    claimed_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT task_claims_student_task_unique UNIQUE (student_id, task_id)
);

CREATE TABLE IF NOT EXISTS public.card_collection (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id bigint NOT NULL,
    milestone_points bigint NOT NULL,
    card_key text NOT NULL,
    set_key text NOT NULL,
    rarity text NOT NULL,
    claimed_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT card_collection_milestone_positive CHECK (milestone_points > 0),
    CONSTRAINT card_collection_rarity_check CHECK (rarity IN ('common', 'rare')),
    CONSTRAINT card_collection_student_milestone_unique UNIQUE (student_id, milestone_points)
);

DO $constraints$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.user_points'::regclass
          AND conname = 'user_points_student_id_fkey'
    ) THEN
        ALTER TABLE public.user_points
            ADD CONSTRAINT user_points_student_id_fkey
            FOREIGN KEY (student_id) REFERENCES public.student (id) ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.task_claims'::regclass
          AND conname = 'task_claims_student_id_fkey'
    ) THEN
        ALTER TABLE public.task_claims
            ADD CONSTRAINT task_claims_student_id_fkey
            FOREIGN KEY (student_id) REFERENCES public.student (id) ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.card_collection'::regclass
          AND conname = 'card_collection_student_id_fkey'
    ) THEN
        ALTER TABLE public.card_collection
            ADD CONSTRAINT card_collection_student_id_fkey
            FOREIGN KEY (student_id) REFERENCES public.student (id) ON DELETE CASCADE NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.card_collection'::regclass
          AND conname = 'card_collection_milestone_positive'
    ) THEN
        ALTER TABLE public.card_collection
            ADD CONSTRAINT card_collection_milestone_positive
            CHECK (milestone_points > 0) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.card_collection'::regclass
          AND conname = 'card_collection_rarity_check'
    ) THEN
        ALTER TABLE public.card_collection
            ADD CONSTRAINT card_collection_rarity_check
            CHECK (rarity IN ('common', 'rare')) NOT VALID;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.task_claims'::regclass
          AND conname = 'task_claims_student_task_unique'
    ) THEN
        ALTER TABLE public.task_claims
            ADD CONSTRAINT task_claims_student_task_unique UNIQUE (student_id, task_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.card_collection'::regclass
          AND conname = 'card_collection_student_milestone_unique'
    ) THEN
        ALTER TABLE public.card_collection
            ADD CONSTRAINT card_collection_student_milestone_unique UNIQUE (student_id, milestone_points);
    END IF;
END
$constraints$;

ALTER TABLE public.user_points VALIDATE CONSTRAINT user_points_student_id_fkey;
ALTER TABLE public.task_claims VALIDATE CONSTRAINT task_claims_student_id_fkey;
ALTER TABLE public.card_collection VALIDATE CONSTRAINT card_collection_student_id_fkey;
ALTER TABLE public.card_collection VALIDATE CONSTRAINT card_collection_milestone_positive;
ALTER TABLE public.card_collection VALIDATE CONSTRAINT card_collection_rarity_check;

CREATE INDEX IF NOT EXISTS task_claims_student_id_idx
    ON public.task_claims (student_id);

CREATE INDEX IF NOT EXISTS card_collection_student_id_idx
    ON public.card_collection (student_id);
